pool:
  vmImage: 'ubuntu-16.04'

steps:
- script: go test -v ./...
  workingDirectory: '$(modulePath)'
  displayName: 'Run tests'

- script: go build -v .
  workingDirectory: '$(modulePath)'
  displayName: 'Build'  